[tox]
requires = tox>=4
env_list = py39, py310, py311, py312, py313, coverage, report, nocoverage

[testenv]
description = Run testing script with lcgp
passenv = COVERAGE_FILE
setenv =
    COV_FILE = {env:COVERAGE_FILE:.coverage}
    DOC_ROOT = docs
deps =
    pandas
    matplotlib
    pytest
    setuptools>=80,<81
extras = test
commands =
    python -m pytest --pyargs lcgp.tests

[testenv:coverage]
description = Run coverage
passenv = COVERAGE_FILE
setenv =
    COV_FILE = {env:COVERAGE_FILE:.coverage}
    DOC_ROOT = docs
deps =
    pandas
    matplotlib
    pytest-cov
    setuptools>=80,<81
extras = test
usedevelop = false
commands =
    coverage run --rcfile={toxinidir}/.coveragerc --data-file={env:COV_FILE} -m pytest ./lcgp/tests


[testenv:nocoverage]
description = Run test suite
deps =
    pandas
    matplotlib
    pytest-cov
    setuptools>=80,<81
extras = test
usedevelop = false
commands =
    python -m pytest ./lcgp/tests


[testenv:ruff]
description = Run ruff
skip_install = true
deps = ruff
commands =
    ruff check lcgp

[testenv:report]
description = Generate coverage report as HTML
depends = coverage
deps = coverage
skip_install = true
passenv = COVERAGE_FILE
setenv =
    COV_FILE = {env:COVERAGE_FILE:.coverage}
commands =
    coverage html   -i --data-file={env:COV_FILE}
    coverage report -i -m --data-file={env:COV_FILE}
