[tox]
requires = tox>=4
env_list = py39, py310, py311, py312, py313, coverage, report, nocoverage

[testenv]
description = Run testing script with lcgp
passenv = COVERAGE_FILE
setenv =
    COV_FILE = {env:COVERAGE_FILE:.coverage}
    DOC_ROOT = docs
deps =
    pandas
    matplotlib
    pytest
    coverage: pytest-cov
    setuptools>=80,<81
extras = test
usedevelop =
    coverage: true
    nocoverage: false
commands =
    nocoverage: python -m pytest --pyargs lcgp.tests
    coverage: coverage run --rcfile={toxinidir}/.coveragerc --data-file={env:COV_FILE} -m pytest {toxinidir}/src/lcgp/tests

[testenv:ruff]
description = Run ruff
skip_install = true
deps = ruff
commands =
    ruff check ./src/lcgp

[testenv:report]
description = Generate coverage report as HTML
depends = coverage
deps = coverage
skip_install = true
commands =
    coverage html   --rcfile={toxinidir}/.coveragerc --data-file={env:COV_FILE}
    coverage report --rcfile={toxinidir}/.coveragerc --data-file={env:COV_FILE}

[testenv:docs]
description = Produce documentation with notebook examples
basepython = py312
change_dir = docs
platform = win32|linux|darwin
deps =
    pandas
    matplotlib
    tensorflow-probability[tf]
    sphinx==6.2.1
    sphinx-book-theme==1.0.1
    sphinxcontrib-bibtex==2.5.0
    sphinx-copybutton==0.5.2
    myst-nb==1.4.0
allowlist_externals =
    cmd
    make
commands =
    win32: cmd /c make.bat html
    linux: make html
    darwin: make html
