name: Python package
env:
  CLONE_PATH:    ${{ github.workspace }}
  COVERAGE_FILE: ${{ github.workspace }}/coverage
  HTML_REPORT:   ${{ github.workspace }}/htmlcov

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  #####----- FULL TESTING WITHOUT COVERAGE
  # Prefer full end-to-end test of local installation via tox's use of pytest.
  build_supported:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Please adjust pyproject.toml Python version requirement to match
        # supported version expressed here.
        os: [ubuntu-latest, windows-latest]  # macos-latest disabled as of now
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Setup Python with tox
      shell: bash
      run: $CLONE_PATH/.github/workflows/install_tox.sh
    - name: Run test suite
      run: |
        pushd $CLONE_PATH
        tox -r -e coverage,report
        popd

    ##-- Publish full coverage report as artifact
    - name: Archive code coverage results
      uses: actions/upload-artifact@v7
      with:
        name: code-coverage-results
        path: |
            ${{ env.COVERAGE_FILE }}
            ${{ env.HTML_REPORT }}

    - name: Upload coverage data
    ##-- Publish full coverage report to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m pip install --upgrade coveralls
        coveralls --service=github --basedir=$CLONE_PATH
